### ISSUE TITLE
Date for release of code, model and data

### ISSUE THREAD

**Issue by caicj15** [mbzuai-oryx/groundingLMM#1]
Nice work!
When will you release code, model and data?

**Comment by hanoonaR** [comment]
Hi @caicj15,

Thank you for your interest in our work! We are excited to share that the code, models, demo, and data will be released soon—expect them in the coming weeks. Please stay updated!

**Comment by QinghongLin** [comment]
looking forward the updates!

**Comment by zhszysrh** [comment]
Will the relevant code of the automatic annotation process and the SG generated in the process also be open source?

**Comment by yangboyd** [comment]
waiting model

**Comment by mmaaz60** [comment]
Hi @zhszysrh,

Thank you for your interest in our work. All the relevant codes and data will be released. Stay tuned as we are working on it. Thanks!

**Comment by michaeljelly** [comment]
Super excited to see it. Results look great. Would be great to have some well-commented training/fine-tuning code as I have some ideas I'd like to experiment with

**Comment by Gutianpei** [comment]
Any update on releasing the code and model weights? The demo looks impressive!

**Comment by chenjun2hao** [comment]
nice work, waiting the code and data!!

**Comment by yangcong356** [comment]
Very valuable work! Looking forward to your code and data releases!

**Comment by hanoonaR** [comment]
Thank you for your interest and patience. Please accept our apologies for the delay in releasing the code and data; our ongoing commitments to PhD courses have required substantial focus recently. We are working on it and plan to release it in approximately two weeks from now.

Thank you for your understanding and continued interest.

**Comment by MSC19950601** [comment]
Very valuable work! Looking forward to your code and data releases!

**Comment by hanoonaR** [comment]
Hi @MSC19950601, @yangcong356, @chenjun2hao, @Gutianpei, @michaeljelly, @QinghongLin, @caicj15,

Thank you for your interest in our work. Please note that we have released the [training and evaluation codes of GLaMM](https://github.com/mbzuai-oryx/groundingLMM?tab=readme-ov-file#-dive-deeper-inside-glamms-training-and-evaluation) along with the pretrained models. Thank You.

**Comment by hanoonaR** [comment]
We are pleased to announce the release of our dataset and the code for the automatic annotation pipeline. You can access the dataset [here](https://github.com/mbzuai-oryx/groundingLMM/blob/main/docs/GranD.md) and find details on the annotation pipeline [here](https://github.com/mbzuai-oryx/groundingLMM/blob/main/docs/GranD.md#grand-automated-annotation-pipeline).
Please let us know if you have any questions. Thank you.
