### ISSUE TITLE
 For further information visit https://errors.pydantic.dev/2.5/v/missing

### ISSUE THREAD

**Issue by hsb1995** [mbzuai-oryx/groundingLMM#10]
Dear professor, could you please answer my question? I completed the installation according to the environment you provided, but the following errors still appeared in the code. The reply chat model you provided has not had a corresponding output statement. The positioning box in this picture can be drawn today.
![image](https://github.com/mbzuai-oryx/groundingLMM/assets/149936473/ecabda22-4aa5-4201-a140-95b9d9d24d2e)
I went to the provided website to check for my local error but was unable to provide relevant information. Please provide an answer. Please.
![image](https://github.com/mbzuai-oryx/groundingLMM/assets/149936473/02f16323-fd57-443d-96d8-24cb5b45784c)

**Comment by hsb1995** [comment]
Gradio version 3.35.2
Gradio-Client version 0.2.7
![image](https://github.com/mbzuai-oryx/groundingLMM/assets/149936473/d9e1e968-d3df-4ef4-ae71-93588546f861)

**Comment by hsb1995** [comment]
Unable to provide a detailed description of the selected area

**Comment by sahalshajim** [comment]
Resolved. Please refer #8
