### ISSUE TITLE
Can you share the `GranD` dataset?

### ISSUE THREAD

**Issue by felixfuu** [mbzuai-oryx/groundingLMM#11]

**Comment by jetyingjia** [comment]
+1

**Comment by hanoonaR** [comment]
Hi @felixfuu and @jetyingjia ,

Thank you for your interest in our work. We just released the [training and evaluation codes of GLaMM](https://github.com/mbzuai-oryx/groundingLMM?tab=readme-ov-file#-dive-deeper-inside-glamms-training-and-evaluation) along with the pretrained models and GranDf dataset. The GranD dataset will be released shortly. We appreciate your patience. Thank you.

**Comment by Glupapa** [comment]
Thanks for the great work. Any updated timeline for releasing GranD dataset and the corresponding pretraining guidelines?

**Comment by SmallWhiteGZ** [comment]
+1

**Comment by felixfuu** [comment]
@hanoonaR

**Comment by hanoonaR** [comment]
Hi @felixfuu, @SmallWhiteGZ, @Glupapa, @jetyingjia 

We are pleased to announce the release of our dataset and the code for the automatic annotation pipeline. You can access the dataset [here](https://github.com/mbzuai-oryx/groundingLMM/blob/main/docs/GranD.md) and find details on the annotation pipeline [here](https://github.com/mbzuai-oryx/groundingLMM/blob/main/docs/GranD.md#grand-automated-annotation-pipeline).
Please let us know if you have any questions. Thank you.
