### ISSUE TITLE
Why are train and val in `GCGBaseDataset` reversed

### ISSUE THREAD

**Issue by xushilin1** [mbzuai-oryx/groundingLMM#12]
Thanks for your great work but is there a mistake here？
https://github.com/mbzuai-oryx/groundingLMM/blob/a9892e657fd140b0c378e8ebe94732c85e22c052/dataset/gcg_datasets/GranDf_gcg_ds.py#L179

**Comment by hanoonaR** [comment]
Hi @xushilin1,

Thank you for your interest in our work and for bringing this to our attention. You are absolutely right – that was indeed a typing error in the file paths. The code has now been [updated](https://github.com/mbzuai-oryx/groundingLMM/blob/b87e8139d8d92d3c8dacafb2c7d9ef6109b6bad1/dataset/gcg_datasets/GranDf_gcg_ds.py#L179
) across all GCG datasets. Please rest assured that despite this mistake in the documentation, the models were trained using the correct splits. Thank you again for your contribution.
