### ISSUE TITLE
how to convert finetune weight to huggingface format?

### ISSUE THREAD

**Issue by garspace** [mbzuai-oryx/groundingLMM#15]
I want to get huggingface model, and inference the huggingface model, the inference code is missing.

**Comment by hanoonaR** [comment]
Hi @garspace,
Thank you for reaching out. To convert fine-tuned weights to the HuggingFace format, please refer to the detailed [instructions](https://github.com/mbzuai-oryx/groundingLMM/blob/main/docs/training.md#merge-lora-weights) provided in our [training documentation](https://github.com/mbzuai-oryx/groundingLMM/blob/main/docs/training.md#merge-lora-weights). Specifically, the section on merging LoRA weights will guide you through the process.

For inference with HuggingFace models, please consult our [evaluation documentation](https://github.com/mbzuai-oryx/groundingLMM/blob/main/docs/evaluation.md), which includes inference code for all models we support.

Hope this helps!

**Comment by hungnh1125** [comment]
Hi. Could you share zero_to_fp32.py file. I cannot find the find in your GitHub.
