### ISSUE TITLE
Question about memory to be used

### ISSUE THREAD

**Issue by tuning12** [mbzuai-oryx/groundingLMM#17]
First thank you for your great work!

I wonder how much VRAM will be used in inference?

Thank you in advance.

**Comment by hanoonaR** [comment]
Hi @tuning12,

Thank you for your interest in our work. Regarding your query about VRAM usage: for optimal performance, our system requires a GPU with at least 24 GB of memory. This specification is detailed in our [offline demo documentation](https://github.com/mbzuai-oryx/groundingLMM/blob/main/docs/offline_demo.md) for your reference.

Please feel free to reach out if you have any more questions. Thank you.

**Comment by tuning12** [comment]
Thank you for your explaination.

I have another question.

Is it possible to segment the specified parts with various masks described in text promt with various masks in the input image with various masks? How to set the prompt?

**Comment by hanoonaR** [comment]
Hi @tuning12,

I'm sorry, I didn't quite understand your question. Are you asking if it's possible to segment multiple parts of an image using by specifying them in the text prompt? Could you please clarify or provide an example?

**Comment by tuning12** [comment]
Sorry, it looks like my comment meets some problem.

For example, I would like to segment the eyes, hair, nose, mouth, neck in an image of human. Is it possible to segment the image with the text prompt?

It is OK to segment one specified part in the image, but how to segment all specified parts in one time with various masks?

Thank you. I hope I make it clear.
