### ISSUE TITLE
Pretraining instructions

### ISSUE THREAD

**Issue by dadaamin** [mbzuai-oryx/groundingLMM#18]
First of all, thank you very much for sharing your amazing work.

I might have missed it, but it looks like there are currently no instructions on how to pretrain a model from scratch. Are you planning to share this too?

**Comment by hanoonaR** [comment]
Hi @dadaamin,

Thank you for your interest in our work. We have now released the pretraining checkpoints, as well as code and documentation for training, evaluation, and checkpoints for finetuning. As for the pretraining and the GranD dataset, we are finalizing them and plan to release them very soon. Stay tuned for these updates, and thank you for your patience!

**Comment by remvanthull** [comment]
When will you be releasing this? :)
