### ISSUE TITLE
For region level captioning, does the model support multi-region inputs?

### ISSUE THREAD

**Issue by HumbleBone** [mbzuai-oryx/groundingLMM#19]
When I read the paper, I found the model can handle  multiple regions as input，Does this mean that if given an image and multiple boxes as input, the model can generate all the region descriptions at once. But when I look at the code, it seems that the model can only caption one box(region) at a time. If I need to generate captions of all the regions in an image, does that mean I have to infer several times? Looking forward to your reply....

**Comment by hanoonaR** [comment]
Hi @HumbleBone ,

Yes, the model can process multiple regions within a single image. To achieve this, you can utilize a structured query format. For instance, you can frame your request as "Can you please describe region1 <bbox1> and region2 <bbox2>?". In this query, the <bbox1> and <bbox2> tokens are placeholders for the representations of the respective regions you wish to describe. The model is designed to replace these <bbox> tokens sequentially with the representations of the corresponding regions based on the order of the box prompts that you provide.

For example, you would get a response like: 
![image](https://github.com/mbzuai-oryx/groundingLMM/assets/58504617/d5953703-2d20-4bb4-ba42-f3d87234a5ae)


I hope this clarifies your query. If you have any further questions or need more detailed guidance, feel free to ask!

**Comment by HumbleBone** [comment]
Hi @hanoonaR 
Thank you for your reply! In this example, does the model generate only one caption for region1 and region2? If I want the model to generate a separate caption of each region, etc, "a man in black" for <region1> and "a motorcycle" for <region2>. can it?

**Comment by hanoonaR** [comment]
Hi @HumbleBone,

Thank you for the clarification. In this scenario you've described, the model generates a single, combined caption that encompasses both region1 and region2 within the same response - as the model is trained to do this to identify how different objects relate with each other. If you are looking to get separate, distinct captions for each region, the current model setup does not support this in a single query. To obtain individual captions for each region, you would need to run separate inferences, one for each region. However, the model can also be tuned to give separate responses.

I hope this helps to clarify the model's capabilities. Thank you.

**Comment by HumbleBone** [comment]
OK, I got it, Thank you very much!
