### ISSUE TITLE
FlashAttention

### ISSUE THREAD

**Issue by ekazakos** [mbzuai-oryx/groundingLMM#23]
Hi,

Thank you for the codebase and the models! I notice that flash attention is one of the dependencies of the project. Since I'm working on AMD GPUs and currently installing flash attention with ROCm support is rather challenging, I was wondering whether the code uses flash attention for training or only in inference. Because if it's used only for training I might skip installing it as I want to use GLaMM mostly for inference. I'm asking this question because I've been looking on another GitHub repo where the instructions suggest to install flash attention only if training is required. Thank you!

**Comment by mmaaz60** [comment]
Hi @ekazakos,

Thank you for your interest in our work. The GLaMM inference should work without FlashAttention. Please let me know if you face any issues and I would be happy to help.

Thanks and Good Luck!

**Comment by ekazakos** [comment]
Thanks for your quick reply! I will give it a go and if I have any issues I will let you know.

**Comment by ekazakos** [comment]
Hi,

The rest of dependencies have been installed ok. But when I try to install mmcv I get:

```
python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      /pfs/lustrep4/users/kazakose/mmcv/setup.py:6: DeprecationWarnin
g: pkg_resources is deprecated as an API. See https://setuptools.pypa
.io/en/latest/pkg_resources.html
        from pkg_resources import DistributionNotFound, get_distribut
ion
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/pfs/lustrep4/users/kazakose/mmcv/setup.py", line 419, in <module>
          ext_modules=get_extensions(),
        File "/pfs/lustrep4/users/kazakose/mmcv/setup.py", line 281, in get_extensions
          hipify_python.hipify(
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/torch/utils/hipify/hipify_python.py", line 1049, in hipify
          preprocess_file_and_save_result(output_directory, filepath, all_files, header_include_dirs,
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/torch/utils/hipify/hipify_python.py", line 182, in preprocess_file_and_save_result
          result = preprocessor(output_directory, filepath, all_files, header_include_dirs, stats,
        File "/project/project_465000880/miniconda3/envs/glamm/lib/python3.10/site-packages/torch/utils/hipify/hipify_python.py", line 752, in preprocessor
          with open(fin_path, 'r', encoding='utf-8') as fin:
      FileNotFoundError: [Errno 2] No such file or directory: '/pfs/lustrep4/users/kazakose/mmcv/mmcv/ops/csrc/mmcv/ops/csrc/common/parrots_cuda_helper.hpp'
      [end of output]
```

It tries to access `mmcv/ops/csrc/mmcv/ops/csrc/common/parrots_cuda_helper.hpp` where the actual path is `mmcv/ops/csrc/common/parrots_cuda_helper.hpp`. Any chance this is an issue of the specific version that you are checking out? Does the code work with other versions?

**Comment by ekazakos** [comment]
Hi,

So I cannot install the modified gradio to run the demo. When trying `bash scripts/build_frontend.sh`, it fails with the following:

```
@gradio/theme@0.0.1 generate /pfs/lustrep4/users/kazakose/gradio-dev/js/theme
pollen -c src/pollen.config.cjs

sh: pollen: command not found
/pfs/lustrep4/users/kazakose/gradio-dev/js/theme:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @gradio/theme@0.0.1 generate: `pollen -c src/pollen.config.cjs`
spawn ENOENT
```

Did you have this issue at all?

**Comment by sahalshajim** [comment]
Hi @ekazakos, you can follow the instructions in https://github.com/ShoufaChen/gradio-box for installing gradio.

**Comment by ekazakos** [comment]
Hi! I get the error after following those instructions.

**Comment by ekazakos** [comment]
I'm closing it as I will not use gradio-box and I will just feed the model with images without using a UI. But please be aware that the installation of gradio-box does not work out of the box in every computer.

**Comment by carlosh93** [comment]
I think the solution to this error

```
@gradio/theme@0.0.1 generate /pfs/lustrep4/users/kazakose/gradio-dev/js/theme
pollen -c src/pollen.config.cjs

sh: pollen: command not found
/pfs/lustrep4/users/kazakose/gradio-dev/js/theme:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @gradio/theme@0.0.1 generate: `pollen -c src/pollen.config.cjs`
spawn ENOENT
```

is to install pollen with pnpm
`pnpm install pollen-css -w`
