### ISSUE TITLE
mmcv version

### ISSUE THREAD

**Issue by ekazakos** [mbzuai-oryx/groundingLMM#24]
Hi,

Currently the code, in particular `mmdet` supports `mmcv` version up to 1.5.0. I tried from 1.4.7 that you suggest up to 1.5.0 and as I'm on AMD GPUs mmcv won't install due to bugs in the ROCm support. Later versions address the issue. I successfully installed mmcv 2.1.0 with ROCm support on AMD GPUs. But due to the current limitation of mmdet that accepts only mmcv versions up to 1.5.0 I cannot properly use the code.

Is there any chance that you could update the code so that mmdet can support mmcv 2.1.0? Thank you.

**Comment by ekazakos** [comment]
Hi,

Actually I simply did it by removing mmdet dir and installing the whole mmdetection package inside groundingLLM. The only breaking change was that `normal_init` now should be imported from `mmengine.model`.

**Comment by iamstuti** [comment]
@ekazakos did you simple execute `pip install mmdet` inside groundingLLM and made `normal_init` to be imported from `mmengine.model`?
Did you also try doing `pip install mmcv-full` as mentioned [here](https://mmdetection.readthedocs.io/en/v2.4.0/install.html) without choosing to compile mmcv from source?
