### ISSUE TITLE
the demo caption is very simple, reproduce the result in paper

### ISSUE THREAD

**Issue by trouble-maker007** [mbzuai-oryx/groundingLMM#25]
the demo caption is very simple, not like the detailed one in the paper, did you limit the output max length?

**Comment by mmaaz60** [comment]
Hi @trouble-maker007,

Thank you for your interest in our work. Could you please share the image and corresponding input prompt that you tried to better assist you?

Thanks

**Comment by trouble-maker007** [comment]
@mmaaz60 sorry for the late response, the caption result is quite simple
<img width="1580" alt="image" src="https://github.com/mbzuai-oryx/groundingLMM/assets/73164596/4811402f-581a-4db8-aabd-9e616aa02b2d">
<img width="1521" alt="image" src="https://github.com/mbzuai-oryx/groundingLMM/assets/73164596/092163e0-f160-455c-9d03-933c253dda03">

**Comment by trouble-maker007** [comment]
@hanoonaR why close, you did not give a response?

**Comment by hanoonaR** [comment]
Hi @trouble-maker007,

Please share the original images, not screenshots. Our model's responses vary with different images. The paper's examples come from various models, including the full-scope GLaMM and the GCG model, which is fine-tuned for grounding interleaved captioning. We haven't set a limit on response length.

**Comment by hanoonaR** [comment]
![demo_result](https://github.com/mbzuai-oryx/groundingLMM/assets/58504617/8ee9c633-6c2a-4374-aabf-faa5cbfc0dca)

Hi @trouble-maker007 , 

We are not facing any issues in reproducing the results in the paper with the live demo.

**Comment by trouble-maker007** [comment]
@hanoonaR  the demo result with the ballon.jpg
<img width="1539" alt="image" src="https://github.com/mbzuai-oryx/groundingLMM/assets/73164596/4a2c0d4b-91f1-4799-9508-72224b54d0c8">
while in  the paper is very detailed
<img width="1046" alt="image" src="https://github.com/mbzuai-oryx/groundingLMM/assets/73164596/53bfe698-cf44-49cb-8c9e-e9e4cbc589d4">
I think there is a big gap
Segment one, lack of the river result
<img width="1573" alt="image" src="https://github.com/mbzuai-oryx/groundingLMM/assets/73164596/5b94c8e4-156d-407d-b882-51e10509c26d">
<img width="1043" alt="image" src="https://github.com/mbzuai-oryx/groundingLMM/assets/73164596/746527fa-c146-4bae-8d90-997e20652de9">

**Comment by hanoonaR** [comment]
Let me clarify a few points:

1) The GLaMM paper covers a broad range of contributions, including detailed analyses of tasks such as image-level captioning and segmentation. Our open-source release includes both a full-scope model and models fine-tuned for specific application. The image captioning results showcased in the particular figure you are showing are from a fine-tuned model.

2) You are trying phrase grounding in the second example -  but the demo model does not support this feature. We have not released this specific model, and accordingly, the demo's instructions do not cover its use. 

3) The generative model is trained on a diverse set of prompts for each task, chosen randomly. This approach can lead to variations in the output. We encourage you to review the quantitative results presented in both the paper and the codebase to better understand the model's capabilities.

Before raising concerns about reproducing results, we urge you to diligently utilize the codebase and the documentation. We can confidently reproduce the results and are here to assist with any genuine issues encountered.

**Comment by trouble-maker007** [comment]
@hanoonaR I still don't fully agree with your explanation for the second case. I only changed one word in your demo example from "this" to "the", and the result changed significantly. This seems to indicate that your model has simply memorized the results for this specific prompt and image, rather than having generalization capabilities.
<img width="1526" alt="image" src="https://github.com/mbzuai-oryx/groundingLMM/assets/73164596/2990f62f-ab08-4626-a244-5c3cd01fb425">
