### ISSUE TITLE
Inference speed

### ISSUE THREAD

**Issue by ekazakos** [mbzuai-oryx/groundingLMM#26]
Hi,

I can successfully now run the code on AMD GPUs but I've noticed that the inference speed is very low. Could this be because I have not installed flash attention (due to the complexity to compile it for AMD) or am I missing something else?

**Comment by mmaaz60** [comment]
Hi @ekazakos,

Thank you, I have also noticed the same on AMD MI250x. I believe this is because of flash attention, however further investigation is required to reach to conclusion and hence a solution. Please do share your findings in case you will be able to figure it out. Thanks.

**Comment by ekazakos** [comment]
Hi,

An update: Flash attention is now installed in my cluster environment and I still experience the same slow inference speed. I do not have an idea yet of what else might be wrong. I will update you if I have some further news.

**Comment by ekazakos** [comment]
Also, I'd like to add that I was chatting with other people from the lab that tried it on NVIDIA GPUS and they also noticed quite slow inference speed. For all of us, inference takes like ~3s per image. Can this just be the size of the model or there might be some bug in the code? Note that I modified the code from the demo.

**Comment by ekazakos** [comment]
So, I did a simple code profiling and found out, not surprisingly, that Greedy Search is the bottleneck. But this might also mean that the LLM runs inefficiently for some reason. Did you experience similar issues and did you take any steps to address it? Can you also please share your hardware setup and inference times? Thank you.
