### ISSUE TITLE
Data release

### ISSUE THREAD

**Issue by saunair** [mbzuai-oryx/groundingLMM#3]
Hi! Loved reading the paper. Is there a release date on the data that you've used to train?

**Comment by hanoonaR** [comment]
Hi @saunair,

Thank you for your interest in our work. We just released the [training and evaluation codes of GLaMM](https://github.com/mbzuai-oryx/groundingLMM?tab=readme-ov-file#-dive-deeper-inside-glamms-training-and-evaluation) along with the pretrained models and GranDf dataset. The GranD dataset will be released shortly. We appreciate your patience. Thank you.

**Comment by saunair** [comment]
Thanks for the response, and the work!
