### ISSUE TITLE
Undefined `self.base_dir` in `GranDfDataset.__init__` 

### ISSUE THREAD

**Issue by function2-llx** [mbzuai-oryx/groundingLMM#30]
Hello, it seems that in the following code, `self.base_dir` is not defined before calling `super().__init__`, and would raise `AttributeError`. 

https://github.com/mbzuai-oryx/groundingLMM/blob/1c04c3b239afcffc830f6e0e6cb1b0565adf4682/dataset/gcg_datasets/GranDf_gcg_ds.py#L160-L173

**Comment by hanoonaR** [comment]
Hi @function2-llx,

Thank you for your interest in our work and for highlighting this issue. We've addressed it in a recent [commit](https://github.com/mbzuai-oryx/groundingLMM/commit/72ed3a8cb2ebb55cf8d5f6d2ef930f4530e79be7). Thanks again for your contribution!
