### ISSUE TITLE
Release of pre-training instructions?

### ISSUE THREAD

**Issue by remvanthull** [mbzuai-oryx/groundingLMM#31]
Hi!

I have recently taken a great interest in your work! However I was wondering: are you planning on releasing the pre-training code/instructions as well? I would love to experiment with training the model from scratch!

Thanks,
Rachel

**Comment by remvanthull** [comment]
Hi @hanoonaR,

Thank you so much for your response!

That is amazing! Very much looking forward to that 😄 Are you by any chance also planning on releasing the code for the automated pipeline for the GranD dataset as well? I'm very interested in that too! Thanks again!

**Comment by hanoonaR** [comment]
Hi @remvanthull,

The upcoming release will indeed include the code for the automated pipeline used to construct the GranD dataset. Additionally, we'll provide detailed instructions on how to convert it into the GLAMM dataset format. Thank you.

**Comment by hanoonaR** [comment]
Hi @remvanthull 

We are pleased to announce the release of our dataset and the code for the automatic annotation pipeline. You can access the dataset [here](https://github.com/mbzuai-oryx/groundingLMM/blob/main/docs/GranD.md) and find details on the annotation pipeline [here](https://github.com/mbzuai-oryx/groundingLMM/blob/main/docs/GranD.md#grand-automated-annotation-pipeline).
Please let us know if you have any questions. Thank you.

**Comment by remvanthull** [comment]
Hi @hanoonaR 

Thank you so much for letting me know! I am very excited to delve into this right away. Just one more question; are you also releasing instructions on how to pre-train GLaMM on GranD? As currently, all code/models are for fine-tuning the pre-trained models. I would very much like to experiment with training from scratch! 😄 

Thank you again!

**Comment by remvanthull** [comment]
Hi @hanoonaR 

Thank you for responding so quickly once again! :) 

What I was wondering is what checkpoint you used to pre-train the model, aka what I should set the —version to, so that I can replicate this pre-training myself; the checkpoints in the model zoo are all already pre-trained, but I’d like to experiment with pre-training :)

Thank you,

Rachel

**Comment by hanoonaR** [comment]
We initialize from LLavA 1.5 (as that's our LLM model).

**Comment by hanoonaR** [comment]
Hi @remvanthull,

Sorry, I forgot to mention that, you will need to set [`--pretrained`](https://github.com/mbzuai-oryx/groundingLMM/blob/c7ee3d7271eda8e9640635ff2ac65651467bc415/train.py#L78) as False. Please let me know if you face any issues in loading the model from LLaVA-1.5 or setting up any dataset. Thank you.
