### ISSUE TITLE
when do you plan to release the dataset?

### ISSUE THREAD

**Issue by alpercanberk** [mbzuai-oryx/groundingLMM#4]

**Comment by ImmortalSdm** [comment]
@hanoonaR   Any ideas? The dataset will be very helpful to the community, looking forward to the release!

**Comment by hanoonaR** [comment]
Hi @ImmortalSdm, @alpercanberk,

Thank you for your interest in our work. We just released the [training and evaluation codes of GLaMM](https://github.com/mbzuai-oryx/groundingLMM?tab=readme-ov-file#-dive-deeper-inside-glamms-training-and-evaluation) along with the pretrained models and GranDf dataset. The GranD dataset will be released shortly. We appreciate your patience. Thank you.

**Comment by hanoonaR** [comment]
Hi @alpercanberk, @ImmortalSdm, 

We are pleased to announce the release of our dataset and the code for the automatic annotation pipeline. You can access the dataset [here](https://github.com/mbzuai-oryx/groundingLMM/blob/main/docs/GranD.md) and find details on the annotation pipeline [here](https://github.com/mbzuai-oryx/groundingLMM/blob/main/docs/GranD.md#grand-automated-annotation-pipeline).
Please let us know if you have any questions. Thank you.

**Comment by uyo9ko** [comment]
Hi @hanoonaR,

Thank you so much for your hard work and dedication to releasing this dataset and the automatic annotation pipeline.

I was reading through the paper and noticed that the GranD dataset is mentioned to include 11 million images and 33 million captions, which is quite impressive. Could you please clarify if the currently released part of the dataset, which contains 1 million images, is the only portion available at this moment? Are there plans to release the remaining parts of the dataset in the near future?

Thank you once again for your contribution and looking forward to your response.

**Comment by mmaaz60** [comment]
Hi @uyo9ko,

Thank you for your interest in our work. Yes, we are working on releasing the remaining parts gradually in coming days.
