### ISSUE TITLE
A bug in region captioning evaluation scripts

### ISSUE THREAD

**Issue by machuofan** [mbzuai-oryx/groundingLMM#40]
Hi, thanks for your great work! I just notice there might be a bug in the `eval/region_captioning/evaluate.py`.

Specifically, when loading generated results from a collection of result files, it uses
~~~
for result_file in os.listdir(args.results_dir):
    all_results = json.load(open(f"{args.results_dir}/{result_file}", "r"))
merged_file_path = f"{args.results_dir}/merged.json"
~~~
At the end, only the results in the last result file are loaded to `all_results`. And the model is essentially evaluated on a subset of test set if we use multiple GPUs for inference.

**Comment by mmaaz60** [comment]
Hi @machuofan,

Thank you for pointing it out. The `eval/region_captioning/evaluate.py` is now updated as follows to solve this issue in case of multi-gpu evaluation.
```
for result_file in os.listdir(args.results_dir):
    all_results += json.load(open(f"{args.results_dir}/{result_file}", "r"))
merged_file_path = f"{args.results_dir}/merged.json"
```

Further, I noticed minor differences in the reported numbers. We will update the `region_captioning` numbers in the next revision of our paper soon. Thank You
