### ISSUE TITLE
Fluctuate results on RefCOCO Family when evaluating the referring expression segmentation.

### ISSUE THREAD

**Issue by Glupapa** [mbzuai-oryx/groundingLMM#42]
Thank you for sharing your great work! 
I am trying to validate the GLaMM-RefSeg model and notice that the performance can vary significantly among different inference times (approximately +/- 1 to 2). Do you have any insights into this phenomenon, or is there any config that I should adjust to achieve more consistent prediction results? Thank you!

**Comment by mmaaz60** [comment]
Hi @Glupapa,

Thank you for your interest in our work. The main reason of this type of fluctuation could be attributed to the dynamic nature of LLM. I would recommend reporting standard deviation by performing inference multiple times in this case.

I tried running RefSeg benchmarks multiple times on RefCOCO and following are the resutls,

```
# RUN 1
[
  {
    "model": "results/refseg",
    "dataset": "refcoco|val",
    "giou": "0.80515635",
    "ciou": "0.7929469"
  },
  {
    "model": "results/refseg",
    "dataset": "refcoco|testA",
    "giou": "0.83403975",
    "ciou": "0.83168846"
  },
  {
    "model": "results/refseg",
    "dataset": "refcoco|testB",
    "giou": "0.776042",
    "ciou": "0.7664252"
  }
]

# RUN 2
[
  {
    "model": "results/refseg",
    "dataset": "refcoco|val",
    "giou": "0.8066321",
    "ciou": "0.7977847"
  },
  {
    "model": "results/refseg",
    "dataset": "refcoco|testA",
    "giou": "0.8239293",
    "ciou": "0.81979144"
  },
  {
    "model": "results/refseg",
    "dataset": "refcoco|testB",
    "giou": "0.7788188",
    "ciou": "0.761931"
  }
]

# RUN 3
[
  {
    "model": "results/refseg",
    "dataset": "refcoco|val",
    "giou": "0.8075647",
    "ciou": "0.80325586"
  },
  {
    "model": "results/refseg",
    "dataset": "refcoco|testA",
    "giou": "0.83058774",
    "ciou": "0.82961744"
  },
  {
    "model": "results/refseg",
    "dataset": "refcoco|testB",
    "giou": "0.7687606",
    "ciou": "0.75880194"
  }
]
```

In summary,

```
ciou (val) - 79.79 with std of 0.419
ciou (testA) - 82.70 with std of 0.519
ciou (testB) - 76.23 with std of 0.312
```

Note that the standard deviations are ranging from 0.3 to 0.6 approx. which is quite reasonable. In some runs (for example Run # 1 & Run # 2 for testA), you may notice a fluctuation of more than 1.0 points, however running the experiment again normalize it with an overall fluctuation of around 0.6 points.

I hope this will help, please let me know if you have any questions. Thank You and Good Luck!
