### ISSUE TITLE
local llm interface for glamm

### ISSUE THREAD

**Issue by whpy** [mbzuai-oryx/groundingLMM#44]
description: glamm performs very well on semantic segmentation. I want to introduce glamm into my multi-agent workflow to solve a sub-task. My multi-agent is constructed by autogen framework.

request: In autogen, we usually provide a local url by litellm for autogen to call other llm model(such as models on ollam), like:
```litellm --model ollama/llama2```
 Is there any similar way for glamm? Thanks!

**Comment by mmaaz60** [comment]
Hi @whpy,

Thank you for your interest in our work. Unfortunately, we do not currently support this. You need to use the code in our repository to use GLaMM. I would recommend consulting the segmentation inference script at [infer_and_evaluate.py](https://github.com/mbzuai-oryx/groundingLMM/blob/main/eval/referring_seg/infer_and_evaluate.py) for more details.

I hope it will help. Please let me know if you have any questions. Thank You
