### ISSUE TITLE
3D implementation of GLaMM

### ISSUE THREAD

**Issue by remvanthull** [mbzuai-oryx/groundingLMM#46]
Hi!

I have been experimenting with your model for quite some time now, specifically on medical imaging data.

I am currently working on looking into possibilities of extending your architecture such that it would be able to encode sequences of images and decode these accordingly to obtain 3D segmentations.

I was curious if you maybe have a take on how to tackle this. It would greatly help me, as I am doing my master's thesis on LMMs in medical imaging with your model as the main focus of interest! :)

Thank you in advance,
Rachel

**Comment by mmaaz60** [comment]
Hi @remvanthull,

Thank you for your interest in our work. Your project looks interesting. A simple approach could be to replace image encoder with something like [UNETR++](https://github.com/Amshaker/unetr_plus_plus) encoder and segmentation decoder with something like [MedSAM](https://github.com/bowang-lab/MedSAM).

Please do share any updates that you may have in your project. Thank you and Good Luck!

**Comment by hanoonaR** [comment]
@remvanthull,

You can checkout [3D-GRAND](https://3d-grand.github.io/)  - Might help in some inspiration in how to extend GLaMM for 3D data.
