### ISSUE TITLE
Can you provide a download link for the pth file of the SAM model?

### ISSUE THREAD

**Issue by MenSanYan** [mbzuai-oryx/groundingLMM#47]
As shown in line 32 of "https://github.com/mbzuai-oryx/groundingLMM/tree/main/scripts/finetune_glamm_refsegm.sh", training requires a SAM pre-trained pth file, but it is not available in Model zoo. Please provide it. @mmaaz60

**Comment by mmaaz60** [comment]
Hi @MenSanYan,

Thank you for your interest in our work. The SAM weights can be downloaded from their official GiTHub repository using the following link,

https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth

**Comment by ekazakos** [comment]
Hi @mmaaz60 ! As I can read in the paper and after checking the code you fine-tuned those weights, correct? Could you provide the fine-tuned SAM weights? Or are these loaded automatically when running `GLaMMForCausalLM.from_pretrained(...)`? That would mean that we should actually pass `--vision_pretrained None` if we actually want to use the fine-tuned weights, right? Thank you!

**Comment by hanoonaR** [comment]
Hi @ekazakos,

The SAM encoder - referred to as the grounding encoder in the paper is frozen. 

During pretraining: we freeze the Grounding encoder [here](https://github.com/mbzuai-oryx/groundingLMM/blob/0c8b252efc5f7b8310bf2f83c3441d78862eb750/model/GLaMM.py#L61).

When we finetune (when you use `from_pretrained`) set gad False [here](https://github.com/mbzuai-oryx/groundingLMM/blob/0c8b252efc5f7b8310bf2f83c3441d78862eb750/train_ft.py#L199). As you can see in this [line](https://github.com/mbzuai-oryx/groundingLMM/blob/0c8b252efc5f7b8310bf2f83c3441d78862eb750/train_ft.py#L268), we do not set grad True for the `grounding_encoder`. 

Hope this helps.
