### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by remvanthull** [mbzuai-oryx/groundingLMM#5]
Hi! Very nice and promising work! When will the code be released? I am really looking forward to experimenting with your code.

**Comment by hanoonaR** [comment]
Hi @remvanthull,

Thank you for your interest in our work. Please note that we have released the [training and evaluation codes of GLaMM](https://github.com/mbzuai-oryx/groundingLMM?tab=readme-ov-file#-dive-deeper-inside-glamms-training-and-evaluation) along with the pretrained models. Thank You.
