### ISSUE TITLE
Online Demo Down

### ISSUE THREAD

**Issue by Shengcao-Cao** [mbzuai-oryx/groundingLMM#51]
Hello Authors of GLaMM,

Thank you for sharing your excellent work!

This is just a notification that your online demo (https://glamm.mbzuai-oryx.ngrok.app) is not working now. Would it be possible to fix it?

Best,
Shengcao

**Comment by mmaaz60** [comment]
Hi @Shengcao-Cao

I appreciate your interest in our work. It's up and running now.

**Comment by HAL-42** [comment]
Hello, authors of GLaMM. 
Thank you for your fantastic work. It appears the online demo is down again. Could you possibly restart it?
The offline demo I set up isn't producing the expected results, so being able to compare it with your online version would be really helpful.

Eg:
Prompt: "Can you segment the hot air balloon ?"
Input Image: The ballon example image.

Output Text: Sure, [SEG] .</s>
Output Image: ![image](https://github.com/user-attachments/assets/e36bffc7-f959-44d7-893c-70a670a5bf1d)
