### ISSUE TITLE
assertion error cur_len == total_len

### ISSUE THREAD

**Issue by bibibabibo26** [mbzuai-oryx/groundingLMM#54]
def _process_conversation(conversation, target, tokenizer, sep, sep2):
    total_len = target.ne(tokenizer.pad_token_id).sum().item()
    rounds = conversation.split(sep2)
    cur_len = 1
    target[:cur_len] = IGNORE_INDEX

    for rou in rounds:
        if not rou:
            break

        parts = rou.split(sep)
        assert len(parts) == 2, (len(parts), rou)
        parts[0] += sep

        if DEFAULT_IMAGE_TOKEN in conversation:
            round_len = len(tokenizer_image_token(rou, tokenizer))
            instruction_len = len(tokenizer_image_token(parts[0], tokenizer)) - 2
        else:
            round_len = len(tokenizer(rou).input_ids)
            instruction_len = len(tokenizer(parts[0]).input_ids) - 2

        target[cur_len: cur_len + instruction_len] = IGNORE_INDEX
        cur_len += round_len

    target[cur_len:] = IGNORE_INDEX
    if cur_len < tokenizer.model_max_length:
        assert cur_len == total_len
when set dataloader to deal with multi-round conversation, it occurs error that cur_len is not equal to total_len, how can I deal with that?

**Comment by mmaaz60** [comment]
Hi @bibibabibo26 

I appreciate your interest in our work. This might be related to the tokenizer. Please ensure that you are using the correct LLM version and using the correct transformers version.

```
pip install transformers@git+https://github.com/huggingface/transformers.git@cae78c46
```

Please let me know if you will be able to solve the issue. Good Luck!
