### ISSUE TITLE
Supplementary materials

### ISSUE THREAD

**Issue by fcjian** [mbzuai-oryx/groundingLMM#6]
Hi! Very nice and promising work! 

Where can I download the supplementary materials？Thank you!

**Comment by hanoonaR** [comment]
Hi @fcjian,

Thank you for your interest in our work! Please find the full paper with supplementary [here](https://github.com/mbzuai-oryx/groundingLMM/blob/main/GLaMM_Full_Paper.pdf). Thank you.
