### ISSUE TITLE
Data Annotation Pipeline

### ISSUE THREAD

**Issue by Luo-Z13** [mbzuai-oryx/groundingLMM#8]
was wondering if it would be possible to make the execution script for the automated annotation pipeline publicly available. I have reviewed the dataset definition in groundingLMM/dataset, but I am uncertain about the process for generating annotations. Any guidance or access to the execution script would be greatly appreciated.

**Comment by hanoonaR** [comment]
Hi @Luo-Z13 ,

Thank you for your interest in our work. The code for downstream application training and evaluation has been made publicly available. We are actively working on releasing the GranD dataset and the annotation pipeline, and we expect to make them available shortly. Thank you for your patience as we make progress. In the meantime, if you have any specific questions regarding the automatic dataset generation pipeline detailed in our paper, please feel free to reach out. We're here to help. Thank you.

**Comment by Luo-Z13** [comment]
> Hi @Luo-Z13 ,
> 
> Thank you for your interest in our work. The code for downstream application training and evaluation has been made publicly available. We are actively working on releasing the GranD dataset and the annotation pipeline, and we expect to make them available shortly. Thank you for your patience as we make progress. In the meantime, if you have any specific questions regarding the automatic dataset generation pipeline detailed in our paper, please feel free to reach out. We're here to help. Thank you.

Okay, thank you very much!
