### ISSUE TITLE
How download images including saiapr_tc-12 under Refer_Segm folder?

### ISSUE THREAD

**Issue by yliu-cs** [mbzuai-oryx/groundingLMM#9]

**Comment by LarsLiden** [comment]
I believe that this is where they can be downloaded but confirmation would be helpful:
https://www-i6.informatik.rwth-aachen.de/imageclef/resources/saiaprtc12/

**Comment by yliu-cs** [comment]
> I believe that this is where they can be downloaded but confirmation would be helpful: https://www-i6.informatik.rwth-aachen.de/imageclef/resources/saiaprtc12/

Thanks! "Referring Expression Segmentation" may not require it; I was able to correctly evaluate on RefCoco without it.

**Comment by hanoonaR** [comment]
Hi @yliu-cs and @LarsLiden,

Thank you both for your interest in our work and for reaching out with your questions.

To clarify, for the RefCLEF portion of our project, the images from the saiapr_tc-12 dataset are indeed necessary. You can download these images from the following link: [saiapr_tc-12 dataset](https://web.archive.org/web/20220515000000/http://bvisionweb1.cs.unc.edu/licheng/referit/data/images/saiapr_tc-12.zip).

Regarding the training process for referring expression segmentation, as outlined in our [training doc](https://github.com/mbzuai-oryx/groundingLMM/blob/b87e8139d8d92d3c8dacafb2c7d9ef6109b6bad1/docs/training.md#3-referring-expression-segmentation-), the model is primarily fine-tuned using the RefCOCO, RefCOCO+, and RefCOCOg datasets. The RefCLEF (saiapr_tc-12) dataset, is utilized for the demo model which uses a mixture of open-source datasets.

I hope this clears up any confusion. If you have any more questions or need further assistance, feel free to ask.
